# Setup
title:            Ian Slay
tagline:          'Tinker'
description:      ''
url:              https://ianslay.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Ian Slay'
  url:            https://github.com/ianslay
  email:          ian@ianslay.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          2.0.0
