# Setup
title:            Ian Slay
tagline:          'Tinker'
description:      ''
url:              https://hyde.getpoole.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Ian Slay'
  url:            ianslay.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
